# Generated by Django 4.2.2 on 2023-06-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='personal.department'),
        ),
    ]
